"""
reactions.py  --  Isodesmic reaction network for neutral coordination complexes
===============================================================================

Builds a directed graph (networkx.DiGraph) where nodes are coordination
complexes and edges are elementary reactions, limited strictly to cases
that are thermodynamically self-consistent at the xTB level.

Scope and limitations
---------------------
This module considers **isodesmic reactions only**: reactions where the
total charge on the left equals the total charge on the right, with all
reference molecules being neutral species.  In practice this means:

  * All complexes in the network must be charge = 0.
  * All complexes must share the same metal oxidation state.
  * Reference species are H2O, HCOOH (and H2 for formation energies).
  * No isolated anions (HCOO-, OH-), no H3O+, no charge-transfer reactions.

Why this restriction?
  xTB energies of isolated anions in the gas phase include no solvation
  correction and are unreliable as absolute references.  For the neutral
  complexes generated by molbuilder (where two anionic ligands balance
  Ni2+), all meaningful ligand exchange reactions cancel the anionic
  character on both sides:

      [Ni-OH] + HCOOH  ->  [Ni-HCOO] + H2O     DeltaE fully valid OK
         neutral  neutral      neutral   neutral

The 1/2H2 convention
  Under the Computational Hydrogen Electrode:  HCOO- = HCOOH - 1/2H2
  For isodesmic reactions where one anionic ligand swaps for another,
  the 1/2H2 terms cancel algebraically and the reaction reduces to:
      [Ni-OH] + HCOOH -> [Ni-HCOO] + H2O   (no H2 appears)
  H2 is tracked as a reference node for future formation-energy uses.

Reactions enumerated
--------------------
SUBSTITUTION   [M(X)(rest)] + acid_Y  ->  [M(Y)(rest)] + acid_X
    where acid_Y / acid_X are the neutral acid forms of ligands Y / X.
    Only pairs with |charge(X)| == |charge(Y)| are included (isodesmic).

ASSOCIATION    monomer + monomer  ->  dimer  (+  displaced H2O)
DISSOCIATION   dimer  ->  monomer + monomer  (+  H2O released)

Bond-broken structures are excluded by default; they are collected in
network.broken_structures for manual review before DFT submission.

Workflow
--------
    rows = run_energetics(...)          # has bond_status column
    net  = ReactionNetwork(rows, mols)
    print(net.summary())
    fig  = net.plot()
    df   = net.to_dataframe()
    hits = net.screen(max_dE=0.5)      # fast pre-DFT screening on DeltaE

Public API
----------
    ReactionNetwork(mols_and_rows, bond_filter=True, verbose=True)
    network.graph              -> nx.DiGraph
    network.substitutions      -> [(src, dst, data), ...]
    network.associations
    network.dissociations
    network.broken_structures  -> [(mol, row), ...] excluded by bond_filter
    network.compute_energies(backend, T, P, ...)
    network.delta_e(src, dst)  -> float | None
    network.delta_g(src, dst)  -> float | None
    network.screen(max_dE, ...)
    network.summary()
    network.node_label(nid)
    network.reaction_str(src, dst)
    network.plot(...)          -> matplotlib.Figure
    network.to_dataframe()     -> pandas.DataFrame
"""

from __future__ import annotations

import re
import warnings
from collections import Counter
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import networkx as nx

from molbuilder.core.molecule import Molecule, Atom
from molbuilder.graph import canonical_hash


# -- constants -----------------------------------------------------------------

class ReactionType:
    SUBSTITUTION    = "substitution"
    COORDINATION    = "coordination"     # ligand added, CN increases
    DECOORDINATION  = "decoordination"   # ligand lost,  CN decreases
    ASSOCIATION     = "association"
    DISSOCIATION    = "dissociation"


# Formal charge of each ligand when coordinated
_LIGAND_CHARGES: Dict[str, int] = {
    "H2O":   0,
    "OH":   -1,
    "HCOO": -1,
    "HCOOH": 0,
    "NH3":   0,
    "Cl":   -1,
    "Br":   -1,
}

# Neutral acid form of each ligand
# [M-OH]  uses H2O   as the neutral reference  (OH- = H2O  - H+, H+ cancels isodesmic)
# [M-HCOO] uses HCOOH as the neutral reference  (HCOO- = HCOOH - H+)
_NEUTRAL_ACID: Dict[str, str] = {
    "H2O":   "H2O",
    "OH":    "H2O",
    "HCOO":  "HCOOH",
    "HCOOH": "HCOOH",
    "NH3":   "NH3",
}


# -- reference molecule geometries ---------------------------------------------

def _make_free_molecule(name: str) -> Optional[Molecule]:
    """Return a simple Molecule for a neutral reference species."""
    if name == "H2O":
        a = np.radians(104.5 / 2); oh = 0.958
        return Molecule(
            atoms=[Atom("O", np.zeros(3)),
                   Atom("H", np.array([ oh*np.sin(a), oh*np.cos(a), 0.])),
                   Atom("H", np.array([-oh*np.sin(a), oh*np.cos(a), 0.]))],
            formula="H2O", charge=0, spin_multiplicity=1, metal_symbol="", metal_ox=0,
        )
    if name == "HCOOH":
        a = np.radians(124.0 / 2); co_d=1.20; co_s=1.34; oh=0.972; ch=1.09
        return Molecule(
            atoms=[Atom("C", np.zeros(3)),
                   Atom("O", np.array([ co_d*np.sin(a), co_d*np.cos(a), 0.])),
                   Atom("O", np.array([-co_s*np.sin(a), co_s*np.cos(a), 0.])),
                   Atom("H", np.array([0., -ch, 0.])),
                   Atom("H", np.array([-co_s*np.sin(a)-oh*0.77,
                                        co_s*np.cos(a)+oh*0.64, 0.]))],
            formula="HCOOH", charge=0, spin_multiplicity=1, metal_symbol="", metal_ox=0,
        )
    if name == "H2":
        return Molecule(
            atoms=[Atom("H", np.array([-0.371, 0., 0.])),
                   Atom("H", np.array([ 0.371, 0., 0.]))],
            formula="H2", charge=0, spin_multiplicity=1, metal_symbol="", metal_ox=0,
        )
    if name == "NH3":
        d = 1.012; a = np.radians(111.5)
        return Molecule(
            atoms=[Atom("N", np.zeros(3)),
                   Atom("H", np.array([d, 0., 0.])),
                   Atom("H", np.array([d*np.cos(np.radians(107.8)),
                                        d*np.sin(np.radians(107.8)), 0.])),
                   Atom("H", np.array([d*np.cos(np.radians(107.8)),
                                       -d*np.sin(np.radians(107.8))*np.cos(np.radians(120.)),
                                        d*np.sin(np.radians(107.8))*np.sin(np.radians(120.))]))],
            formula="NH3", charge=0, spin_multiplicity=1, metal_symbol="", metal_ox=0,
        )
    return None


def _ref_id(name: str) -> str:
    return f"ref:{name}"


# -- helpers -------------------------------------------------------------------

def _parse_combo(combo: str) -> Counter:
    """'H2O3_HCOO2' -> Counter({'H2O': 3, 'HCOO': 2})."""
    counts: Counter = Counter()
    for part in combo.split("_"):
        if not part:
            continue
        m = re.match(r"([A-Za-z0-9:]+?)(\d+)$", part)
        if m:
            counts[m.group(1)] += int(m.group(2))
        else:
            counts[part] += 1
    return counts


def _is_isodesmic(outgoing: str, incoming: str) -> bool:
    """True when the two ligands have the same formal charge."""
    return _LIGAND_CHARGES.get(outgoing, 0) == _LIGAND_CHARGES.get(incoming, 0)


def _substitution_stoich(
    nid_src: str,
    nid_dst: str,
    outgoing: str,
    incoming: str,
    n_m: int,
) -> Dict[str, int]:
    """
    Build stoichiometry dict for:
        n_m x outgoing (leaves complex) + n_m x acid(incoming) ->
        n_m x incoming (enters complex) + n_m x acid(outgoing)

    All references are neutral acids; the reaction is isodesmic by construction.
    """
    ref_in  = _ref_id(_NEUTRAL_ACID.get(incoming, incoming))
    ref_out = _ref_id(_NEUTRAL_ACID.get(outgoing, outgoing))
    # If both refs are identical (e.g. H2O<->H2O swap) the stoich cancels
    stoich: Dict[str, int] = {nid_src: -1, nid_dst: +1}
    if ref_in == ref_out:
        pass   # refs cancel: net 0 change in reference
    else:
        stoich[ref_in]   = stoich.get(ref_in,  0) - n_m
        stoich[ref_out]  = stoich.get(ref_out, 0) + n_m
    return stoich


# -- ReactionNetwork ----------------------------------------------------------

class ReactionNetwork:
    """
    Isodesmic reaction network for neutral Ni coordination complexes.

    Parameters
    ----------
    mols_and_rows : list of (Molecule, row_dict) from enumerate_complexes()
                    or run_energetics().  row_dict must contain at minimum
                    'metal', 'ox', 'cn', 'geometry', 'ligand_combo', 'charge'.
    bond_filter   : Exclude structures with bond_status == "BROKEN".
                    Excluded structures are in self.broken_structures.
    include_geometry_changes : Also enumerate substitutions across geometries.
    verbose       : Print counts and warnings to stdout.
    """

    def __init__(
        self,
        mols_and_rows: List[Tuple[Molecule, Dict[str, Any]]],
        bond_filter:  bool = True,
        include_geometry_changes: bool = False,
        verbose: bool = True,
    ) -> None:
        self._incl_geom = include_geometry_changes
        self.graph: nx.DiGraph = nx.DiGraph()
        self._hash_to_nid: Dict[tuple, str] = {}

        # -- bond filter -------------------------------------------------------
        self.broken_structures: List[Tuple[Molecule, Dict[str, Any]]] = []
        good: List[Tuple[Molecule, Dict[str, Any]]] = []
        for mol, row in mols_and_rows:
            if bond_filter and row.get("bond_status") == "BROKEN":
                self.broken_structures.append((mol, row))
            else:
                good.append((mol, row))

        if self.broken_structures and verbose:
            n = len(self.broken_structures)
            formulas = ", ".join(m.formula for m, _ in self.broken_structures[:4])
            print(f"  !  {n} structure(s) excluded (bond_status=BROKEN): {formulas}"
                  + ("..." if n > 4 else ""))
            print("     Access via network.broken_structures for manual review.")

        # -- neutral filter ----------------------------------------------------
        non_neutral = [(mol, row) for mol, row in good if mol.charge != 0]
        if non_neutral and verbose:
            n = len(non_neutral)
            print(f"  i  {n} structure(s) with charge != 0 kept but will not form "
                  "isodesmic edges with charge=0 structures.")

        # -- build graph -------------------------------------------------------
        self._free: Dict[str, Molecule] = {}
        for name in ("H2O", "HCOOH", "H2"):
            mol_ref = _make_free_molecule(name)
            if mol_ref:
                self._free[name] = mol_ref

        self._add_inventory_nodes(good)
        self._add_reference_nodes()
        self._enumerate_substitutions(good)
        self._enumerate_cn_changes(good)
        self._enumerate_associations(good)

        if verbose:
            n_sub   = len(self.substitutions) // 2
            n_cn    = len(self.coordinations) // 2
            n_assoc = len(self.associations)
            print(f"  ReactionNetwork: {len(good)} complexes, "
                  f"{n_sub} substitution, "
                  f"{n_cn} coordination/decoordination, "
                  f"{n_assoc} association reactions.")

    # -- node construction -----------------------------------------------------

    def _add_inventory_nodes(self, mols_and_rows) -> None:
        for mol, row in mols_and_rows:
            h   = canonical_hash(mol)
            nid = self._hash_to_nid.get(h)
            if nid is None:
                nid = h
                self._hash_to_nid[h] = nid
                self.graph.add_node(nid,
                    mol         = mol,
                    row         = row,
                    formula     = mol.formula,
                    charge      = mol.charge,
                    structure   = row.get("structure", ""),
                    geometry    = row.get("geometry", ""),
                    cn          = row.get("cn", 0),
                    ligands     = row.get("ligand_combo", ""),
                    ox_label    = row.get("ox_label", ""),
                    ox          = row.get("ox", 0),
                    bond_status = row.get("bond_status", "OK"),
                    energy_eV   = row.get("relax_energy_eV"),
                    gibbs_eV    = row.get("relax_gibbs_eV"),
                    _therm      = None,
                    node_type   = "complex",
                )

    def _add_reference_nodes(self) -> None:
        for name, mol in self._free.items():
            nid = _ref_id(name)
            if nid not in self.graph:
                self.graph.add_node(nid,
                    mol=mol, row={}, formula=mol.formula, charge=mol.charge,
                    structure="free", geometry="", cn=0, ligands=name,
                    ox_label="", ox=None, bond_status="OK",
                    energy_eV=None, gibbs_eV=None, _therm=None,
                    node_type="reference",
                )

    # -- substitution enumeration ----------------------------------------------

    def _enumerate_substitutions(self, mols_and_rows) -> None:
        """
        For each pair (A, B) of complex nodes:
          - same metal and oxidation state
          - same coordination number and geometry (unless include_geometry_changes)
          - differ by exactly one ligand per metal
          - the swap is isodesmic: |charge(outgoing)| == |charge(incoming)|
        """
        nodes = [(nid, d) for nid, d in self.graph.nodes(data=True)
                 if d["node_type"] == "complex"]

        for i, (nidA, dA) in enumerate(nodes):
            for j, (nidB, dB) in enumerate(nodes):
                if i >= j:
                    continue

                rowA, rowB = dA["row"], dB["row"]
                molA, molB = dA["mol"], dB["mol"]

                # Same metal and oxidation state
                if rowA.get("metal") != rowB.get("metal"):
                    continue
                if rowA.get("ox") != rowB.get("ox"):
                    continue

                # Same coordination number
                if rowA.get("cn") != rowB.get("cn"):
                    continue

                # Same geometry (unless overridden)
                if not self._incl_geom:
                    if rowA.get("geometry") != rowB.get("geometry"):
                        continue

                # Same nuclearity
                n_m_A = len(molA.metal_indices) if hasattr(molA, "metal_indices") else 1
                n_m_B = len(molB.metal_indices) if hasattr(molB, "metal_indices") else 1
                if n_m_A != n_m_B:
                    continue
                n_m = n_m_A

                # Ligand difference: exactly 1 ligand per metal swapped
                ligsA = _parse_combo(rowA.get("ligand_combo", ""))
                ligsB = _parse_combo(rowB.get("ligand_combo", ""))
                all_l = set(ligsA) | set(ligsB)
                removed = {k: ligsA.get(k,0)-ligsB.get(k,0) for k in all_l
                           if ligsA.get(k,0) > ligsB.get(k,0)}
                added   = {k: ligsB.get(k,0)-ligsA.get(k,0) for k in all_l
                           if ligsB.get(k,0) > ligsA.get(k,0)}

                if sum(removed.values()) != 1 or sum(added.values()) != 1:
                    continue

                out_lig = next(iter(removed))
                in_lig  = next(iter(added))

                # ISODESMIC CHECK: same ligand charge on both sides
                if not _is_isodesmic(out_lig, in_lig):
                    continue

                # Verify molecular charge balance is consistent
                q_in  = _LIGAND_CHARGES.get(in_lig,  0)
                q_out = _LIGAND_CHARGES.get(out_lig, 0)
                expected_dq = (q_in - q_out) * n_m
                if molB.charge - molA.charge != expected_dq:
                    continue

                # Make sure required reference nodes exist in graph
                for lig in (in_lig, out_lig):
                    ref_name = _NEUTRAL_ACID.get(lig, lig)
                    rid = _ref_id(ref_name)
                    if rid not in self.graph:
                        mol_ref = _make_free_molecule(ref_name)
                        if mol_ref:
                            self.graph.add_node(rid,
                                mol=mol_ref, row={}, formula=mol_ref.formula,
                                charge=0, structure="free", geometry="", cn=0,
                                ligands=ref_name, ox_label="", ox=None,
                                bond_status="OK", energy_eV=None, gibbs_eV=None,
                                _therm=None, node_type="reference",
                            )

                # Build stoichiometry and add edges (both directions)
                n_x = n_m
                lbl = lambda a, b: f"{n_x}x{a}->{n_x}x{b}" if n_x > 1 else f"{a}->{b}"

                stoich_fwd = _substitution_stoich(nidA, nidB, out_lig, in_lig,  n_m)
                stoich_rev = _substitution_stoich(nidB, nidA, in_lig,  out_lig, n_m)

                ref_in_name  = _NEUTRAL_ACID.get(in_lig,  in_lig)
                ref_out_name = _NEUTRAL_ACID.get(out_lig, out_lig)

                for src, dst, stch, l_in, l_out, rn_in, rn_out in [
                    (nidA, nidB, stoich_fwd, in_lig,  out_lig, ref_in_name,  ref_out_name),
                    (nidB, nidA, stoich_rev, out_lig, in_lig,  ref_out_name, ref_in_name),
                ]:
                    # Mark edges where HCOOH is the incoming reference --
                    # these represent the formic acid route:
                    # HCOOH + [Ni-OH] -> [Ni-HCOO] + H2O
                    is_hcooh_reaction = (rn_in == "HCOOH")
                    self.graph.add_edge(src, dst,
                        reaction_type = ReactionType.SUBSTITUTION,
                        incoming      = l_in,
                        outgoing      = l_out,
                        n_exchanged   = n_m,
                        ref_in        = _ref_id(rn_in),
                        ref_out       = _ref_id(rn_out),
                        hcoo_source   = is_hcooh_reaction,
                        stoich        = stch,
                        delta_e       = None,
                        delta_g       = None,
                        label         = lbl(l_in, l_out),
                    )

    # -- coordination / decoordination enumeration -----------------------------

    def _enumerate_cn_changes(self, mols_and_rows) -> None:
        """
        Add COORDINATION and DECOORDINATION edges for CN+/-1 reactions.

        A COORDINATION reaction:
            [M(L)_n] + H2O  ->  [M(L)_n(H2O)]        (CN increases by 1)

        A DECOORDINATION reaction:
            [M(L)_n(H2O)]   ->  [M(L)_n] + H2O        (CN decreases by 1)

        Only H2O gain/loss is considered (isodesmic -- H2O is neutral, no
        charge change).  Adding an anionic ligand (HCOO-, OH-) would change
        total charge, violating the isodesmic constraint.

        Both structures may have different geometries (tet->sqpy, sqpy->oct etc.),
        which is correct: CN changes always involve a geometry rearrangement.

        Constraint: same metal, same oxidation state, same non-H2O ligand set,
        CN differs by exactly 1, only H2O count changes.

        **Gas-phase interpretation warning**

        DeltaE for coordination is *always* negative in gas phase -- forming any
        new M-L bond lowers electronic energy.  This does NOT mean higher CN
        is always preferred; in solution, solvated H2O competes with coordinated
        H2O (DeltaG_solvation ~= 0.4-0.5 eV per water molecule).

        Use these DeltaE values for *relative ranking within your inventory only*:
        e.g. "which of the CN=5 structures is closest in energy to CN=6 oct?"
        To predict preferred CN in solution you need an implicit solvation model
        (COSMO-RS, SMD) or explicit solvent DFT.

        The DeltaG from compute_thermo=True includes ZPE and entropy corrections
        for the gas-phase H2O reference, which partially reduces the bias, but
        the solvation term is still missing.
        """
        nodes = [(nid, d) for nid, d in self.graph.nodes(data=True)
                 if d["node_type"] == "complex" and d["structure"] == "monomer"]

        ref_h2o = _ref_id("H2O")

        for i, (nidA, dA) in enumerate(nodes):
            for j, (nidB, dB) in enumerate(nodes):
                if i >= j:
                    continue

                rowA, rowB = dA["row"], dB["row"]
                molA, molB = dA["mol"], dB["mol"]

                if rowA.get("metal") != rowB.get("metal"): continue
                if rowA.get("ox")    != rowB.get("ox"):    continue

                cn_diff = rowB.get("cn", 0) - rowA.get("cn", 0)
                if abs(cn_diff) != 1:
                    continue

                ligsA = _parse_combo(rowA.get("ligand_combo", ""))
                ligsB = _parse_combo(rowB.get("ligand_combo", ""))
                la_nw = {k: v for k, v in ligsA.items() if k != "H2O"}
                lb_nw = {k: v for k, v in ligsB.items() if k != "H2O"}
                if la_nw != lb_nw:
                    continue

                dh2o = ligsB.get("H2O", 0) - ligsA.get("H2O", 0)
                if dh2o != cn_diff:
                    continue

                # Isodesmic: H2O is neutral so charges must be equal
                if molA.charge != molB.charge:
                    continue

                if cn_diff > 0:
                    nid_lo, nid_hi = nidA, nidB
                    row_lo, row_hi = rowA, rowB
                else:
                    nid_lo, nid_hi = nidB, nidA
                    row_lo, row_hi = rowB, rowA

                stoich_coord   = {nid_lo: -1, ref_h2o: -1, nid_hi: +1}
                stoich_decoord = {nid_hi: -1, nid_lo: +1, ref_h2o: +1}

                lbl_c = (f"CN{row_lo['cn']}[{row_lo['geometry']}]"
                         f"->CN{row_hi['cn']}[{row_hi['geometry']}]")
                lbl_d = (f"CN{row_hi['cn']}[{row_hi['geometry']}]"
                         f"->CN{row_lo['cn']}[{row_lo['geometry']}]")

                self.graph.add_edge(nid_lo, nid_hi,
                    reaction_type = ReactionType.COORDINATION,
                    gained_ligand = "H2O",
                    cn_from       = row_lo["cn"],
                    cn_to         = row_hi["cn"],
                    geom_from     = row_lo.get("geometry", ""),
                    geom_to       = row_hi.get("geometry", ""),
                    stoich        = stoich_coord,
                    delta_e       = None, delta_g = None,
                    label         = lbl_c,
                )
                self.graph.add_edge(nid_hi, nid_lo,
                    reaction_type = ReactionType.DECOORDINATION,
                    lost_ligand   = "H2O",
                    cn_from       = row_hi["cn"],
                    cn_to         = row_lo["cn"],
                    geom_from     = row_hi.get("geometry", ""),
                    geom_to       = row_lo.get("geometry", ""),
                    stoich        = stoich_decoord,
                    delta_e       = None, delta_g = None,
                    label         = lbl_d,
                )

    # -- association / dissociation enumeration --------------------------------

    def _enumerate_associations(self, mols_and_rows) -> None:
        """
        For each (monomer, dimer) pair with matching metal / oxidation state:
        add 2xmono -> dimer + displaced_ligands (and reverse dissociation).

        The displaced ligand set is derived from the actual ligand arithmetic
        (monomer ligands minus dimer terminal ligands) rather than being
        hard-coded to H2O.  The reaction is only added when all displaced
        ligands are neutral (isodesmic constraint).
        """
        monomers = [(nid, d) for nid, d in self.graph.nodes(data=True)
                    if d["node_type"] == "complex" and d["structure"] == "monomer"]
        dimers   = [(nid, d) for nid, d in self.graph.nodes(data=True)
                    if d["node_type"] == "complex" and d["structure"] == "dimer"]

        for nid_d, dd in dimers:
            mol_d, row_d = dd["mol"], dd["row"]

            for nid_m, dm in monomers:
                mol_m, row_m = dm["mol"], dm["row"]

                if row_m.get("metal") != row_d.get("metal"):  continue
                if row_m.get("ox")    != row_d.get("ox"):     continue

                bridge    = row_d.get("bridge", "")
                n_bridges = row_d.get("n_bridges", 0)
                mon_cn    = row_m.get("cn", 0)
                dimer_cn  = row_d.get("cn", 0)
                n_disp    = mon_cn - (dimer_cn - n_bridges)

                if n_disp < 0:
                    continue

                # Work out which ligands are actually displaced by comparing
                # 2x monomer ligand set vs dimer ligand set.
                # displaced = 2*monomer_ligands - dimer_ligands (excluding bridges)
                ligs_mono  = _parse_combo(row_m.get("ligand_combo", ""))
                ligs_dimer = _parse_combo(row_d.get("ligand_combo", ""))
                # The bridge ligands appear in the dimer combo; subtract them
                bridge_lig = bridge.replace("mu-", "") if bridge else None

                combined_mono = Counter({k: v * 2 for k, v in ligs_mono.items()})
                displaced_counter = combined_mono - ligs_dimer
                # Remove bridge contribution (bridges come from both monomers)
                if bridge_lig and bridge_lig in displaced_counter:
                    displaced_counter[bridge_lig] = max(
                        0, displaced_counter[bridge_lig] - n_bridges)
                    if displaced_counter[bridge_lig] == 0:
                        del displaced_counter[bridge_lig]

                if not displaced_counter:
                    continue

                # Isodesmic check: all displaced ligands must be neutral
                displaced_charge = sum(
                    _LIGAND_CHARGES.get(lig, 0) * cnt
                    for lig, cnt in displaced_counter.items()
                )
                if displaced_charge != 0:
                    continue

                # Verify charge balance: 2*q_mono == q_dimer + displaced_charge
                if 2 * mol_m.charge != mol_d.charge + displaced_charge:
                    continue

                # Ensure reference nodes exist for every displaced ligand
                stoich_assoc = {nid_m: -2, nid_d: +1}
                for lig, cnt in displaced_counter.items():
                    ref_name = _NEUTRAL_ACID.get(lig, lig)
                    rid = _ref_id(ref_name)
                    if rid not in self.graph:
                        mol_ref = _make_free_molecule(ref_name)
                        if mol_ref:
                            self.graph.add_node(rid,
                                mol=mol_ref, row={}, formula=mol_ref.formula,
                                charge=0, structure="free", geometry="", cn=0,
                                ligands=ref_name, ox_label="", ox=None,
                                bond_status="OK", energy_eV=None, gibbs_eV=None,
                                _therm=None, node_type="reference",
                            )
                    stoich_assoc[rid] = stoich_assoc.get(rid, 0) + cnt

                stoich_diss = {v: -k for v, k in stoich_assoc.items()}

                disp_str = "+".join(
                    f"{cnt}x{lig}" if cnt > 1 else lig
                    for lig, cnt in sorted(displaced_counter.items())
                )

                self.graph.add_edge(nid_m, nid_d,
                    reaction_type    = ReactionType.ASSOCIATION,
                    n_monomers       = 2,
                    bridge           = bridge,
                    n_bridges        = n_bridges,
                    n_displaced      = sum(displaced_counter.values()),
                    displaced_ligand = disp_str,
                    stoich           = stoich_assoc,
                    delta_e          = None,
                    delta_g          = None,
                    label            = f"2xmono->dimer+{disp_str}",
                )
                self.graph.add_edge(nid_d, nid_m,
                    reaction_type    = ReactionType.DISSOCIATION,
                    n_monomers       = 2,
                    bridge           = bridge,
                    n_bridges        = n_bridges,
                    n_displaced      = sum(displaced_counter.values()),
                    displaced_ligand = disp_str,
                    stoich           = stoich_diss,
                    delta_e          = None,
                    delta_g          = None,
                    label            = f"dimer->2xmono+{disp_str}",
                )

    # -- energy computation ----------------------------------------------------

    def compute_energies(
        self,
        backend:         str   = "xtb",
        model:           Optional[str] = None,
        compute_thermo:  bool  = True,
        T:               float = 298.15,
        P:               float = 101325.0,
        fmax:            float = 0.05,
        steps:           int   = 300,
        device:          str   = "cpu",
        constrain_bonds: bool  = False,
        verbose:         bool  = True,
    ) -> None:
        """
        Compute xTB (or MACE) energies for every node and attach DeltaE / DeltaG to edges.

        All reference molecules (H2O, HCOOH, H2) are also computed as
        neutral gas-phase species.  DeltaE values for isodesmic reactions are
        reliable without any solvation correction.
        """
        try:
            from molbuilder.relaxation import relax, thermochemistry
        except ImportError as exc:
            raise ImportError("pip install tblite ase  (for xTB)") from exc

        n = self.graph.number_of_nodes()
        if verbose:
            kind = "E + G(T,P)" if compute_thermo else "E"
            print(f"Computing {backend} {kind} for {n} nodes ...")

        for idx, (nid, data) in enumerate(self.graph.nodes(data=True)):
            mol = data.get("mol")
            if mol is None:
                continue
            if verbose:
                lbl = data.get("formula", "?")
                print(f"  [{idx+1}/{n}] {lbl:20s} ... ", end="", flush=True)
            try:
                if compute_thermo:
                    res = thermochemistry(
                        mol, backend=backend, model=model,
                        T=T, P=P, fmax=fmax, steps=steps,
                        device=device, constrain_bonds=constrain_bonds,
                    )
                    self.graph.nodes[nid].update(
                        energy_eV=float(res.energy_eV),
                        gibbs_eV =float(res.gibbs_eV),
                        _therm   =res,
                    )
                    if verbose:
                        print(f"E={res.energy_eV:.3f}  G={res.gibbs_eV:.3f} eV")
                else:
                    res = relax(
                        mol, backend=backend, model=model,
                        fmax=fmax, steps=steps, device=device,
                        constrain_bonds=constrain_bonds,
                    )
                    self.graph.nodes[nid]["energy_eV"] = float(res.energy_eV)
                    if verbose:
                        print(f"E={res.energy_eV:.3f} eV")
            except Exception as exc:
                if verbose:
                    print(f"FAILED: {exc}")
                warnings.warn(f"Energy failed for {data.get('formula','?')}: {exc}")

        self._update_edge_energies(T, P)

    def _update_edge_energies(self, T=298.15, P=101325.0) -> None:
        for src, dst, e in self.graph.edges(data=True):
            dE = self._stoich_sum(e.get("stoich", {}), "energy_eV")
            dG = self._stoich_sum(e.get("stoich", {}), "gibbs_eV")
            self.graph[src][dst]["delta_e"] = dE
            self.graph[src][dst]["delta_g"] = dG

    def _stoich_sum(self, stoich: dict, key: str) -> Optional[float]:
        total = 0.0
        for nid, coeff in stoich.items():
            val = self.graph.nodes.get(nid, {}).get(key)
            if val is None:
                return None
            total += coeff * val
        return total

    # -- accessors -------------------------------------------------------------

    def delta_e(self, src, dst) -> Optional[float]:
        if not self.graph.has_edge(src, dst):
            return None
        return self.graph[src][dst].get("delta_e")

    def delta_g(self, src, dst, T: float = 298.15, P: float = 101325.0) -> Optional[float]:
        if not self.graph.has_edge(src, dst):
            return None
        stored = self.graph[src][dst].get("delta_g")
        if stored is not None:
            return stored
        stoich = self.graph[src][dst].get("stoich", {})
        total = 0.0
        for nid, coeff in stoich.items():
            tr = self.graph.nodes.get(nid, {}).get("_therm")
            if tr is None:
                return None
            try:
                total += coeff * tr.gibbs_at(T=T, P=P)
            except Exception:
                return None
        return total

    def screen(
        self,
        max_dE:          float = 0.5,
        T:               float = 298.15,
        P:               float = 101325.0,
        reaction_types:  Optional[List[str]] = None,
        use_gibbs:       bool  = True,
        require_energy:  bool  = True,
    ) -> List[Tuple]:
        """
        Return edges whose DeltaE (or DeltaG) <= max_dE eV, sorted ascending.

        All returned edges are isodesmic by construction.

        Parameters
        ----------
        max_dE        : Upper bound in eV.
        use_gibbs     : Screen on DeltaG instead of DeltaE (requires thermo).
        require_energy: Skip edges with no energy computed.
        """
        results = []
        for src, dst, e in self.graph.edges(data=True):
            if reaction_types and e.get("reaction_type") not in reaction_types:
                continue
            val = (self.delta_g(src, dst, T, P) if use_gibbs
                   else e.get("delta_e"))
            if val is None:
                if require_energy:
                    continue
            elif val <= max_dE:
                results.append((src, dst, e, val))
        results.sort(key=lambda x: x[3] if x[3] is not None else float("inf"))
        return results

    # -- convenience properties ------------------------------------------------

    @property
    def nodes(self): return list(self.graph.nodes)

    @property
    def edges(self): return list(self.graph.edges(data=True))

    @property
    def substitutions(self):
        return [(s,d,e) for s,d,e in self.edges
                if e.get("reaction_type") == ReactionType.SUBSTITUTION]

    @property
    def associations(self):
        return [(s,d,e) for s,d,e in self.edges
                if e.get("reaction_type") == ReactionType.ASSOCIATION]

    @property
    def dissociations(self):
        return [(s,d,e) for s,d,e in self.edges
                if e.get("reaction_type") == ReactionType.DISSOCIATION]

    @property
    def coordinations(self):
        """COORDINATION edges: CN increases by 1 (gain H2O)."""
        return [(s,d,e) for s,d,e in self.edges
                if e.get("reaction_type") == ReactionType.COORDINATION]

    @property
    def decoordinations(self):
        """DECOORDINATION edges: CN decreases by 1 (lose H2O)."""
        return [(s,d,e) for s,d,e in self.edges
                if e.get("reaction_type") == ReactionType.DECOORDINATION]

    # -- summary, labels, reaction string -------------------------------------

    def summary(self) -> str:
        n_c   = sum(1 for _,d in self.graph.nodes(data=True) if d["node_type"]=="complex")
        n_r   = sum(1 for _,d in self.graph.nodes(data=True) if d["node_type"]=="reference")
        n_sub = len(self.substitutions) // 2
        n_cn  = len(self.coordinations) // 2
        n_as  = len(self.associations)
        n_ds  = len(self.dissociations)
        n_e   = sum(1 for _,d in self.graph.nodes(data=True) if d.get("energy_eV") is not None)
        n_g   = sum(1 for _,d in self.graph.nodes(data=True) if d.get("gibbs_eV")  is not None)
        n_br  = len(self.broken_structures)
        return "\n".join([
            "ReactionNetwork  (isodesmic, neutral species only)",
            f"  Complex nodes          : {n_c}",
            f"  Reference nodes        : {n_r}  (H2O, HCOOH, H2)",
            f"  Excluded -- BROKEN      : {n_br}  -> see network.broken_structures",
            f"  Substitutions          : {n_sub}  ({2*n_sub} directed edges)",
            f"  Coordination / Decoord : {n_cn}  ({2*n_cn} directed edges, CN+/-1 via H2O)",
            f"  Associations           : {n_as}   Dissociations: {n_ds}",
            f"  Nodes with E           : {n_e} / {n_c + n_r}",
            f"  Nodes with G(T,P)      : {n_g} / {n_c + n_r}",
            "",
            "  All reactions are isodesmic (neutral refs, same total charge).",
            "  Substitutions:   [Ni-OH] + HCOOH  ->  [Ni-HCOO] + H2O",
            "  Coordination:    [Ni(L)_n] + H2O  ->  [Ni(L)_n(H2O)]  (CN+/-1)",
            "  1/2H2 cancels algebraically; no explicit H2 terms in current stoich.",
            "",
            "  !  GAS PHASE CAVEAT for coordination/decoordination:",
            "     DeltaE is always negative (M-L bond formation).  Use DeltaE only for",
            "     relative ranking within your inventory, NOT to predict preferred CN.",
            "     Solution-phase preference requires an implicit solvation correction.",
        ])


    def node_label(self, nid) -> str:
        d = self.graph.nodes.get(nid, {})
        if d.get("node_type") == "reference":
            return f"ref:{d.get('ligands','?')}"
        geom = d.get("geometry","")
        ligs = d.get("ligands","")
        ox   = d.get("ox_label","")
        return f"{ox} [{geom}] {ligs}".strip() or str(nid)[:20]

    def reaction_str(self, src, dst) -> str:
        if not self.graph.has_edge(src, dst):
            return "No such edge"
        e     = self.graph[src][dst]
        rtype = e.get("reaction_type","")
        sl    = self.node_label(src)
        dl    = self.node_label(dst)
        dE    = e.get("delta_e")
        dG    = e.get("delta_g")

        if rtype == ReactionType.SUBSTITUTION:
            n        = e.get("n_exchanged",1)
            ref_in   = e.get("ref_in","").replace("ref:","")
            ref_out  = e.get("ref_out","").replace("ref:","")
            px       = f"{n}x" if n > 1 else ""
            if ref_in == ref_out or not ref_in:
                rxn = f"[{sl}]  ->  [{dl}]  (isomer)"
            else:
                rxn = f"[{sl}] + {px}{ref_in}  ->  [{dl}] + {px}{ref_out}"
        elif rtype == ReactionType.COORDINATION:
            cf  = e.get("cn_from","?"); ct = e.get("cn_to","?")
            gf  = e.get("geom_from",""); gt = e.get("geom_to","")
            rxn = f"[{sl}] + H2O  ->  [{dl}]  (CN{cf}[{gf}]->CN{ct}[{gt}])"
        elif rtype == ReactionType.DECOORDINATION:
            cf  = e.get("cn_from","?"); ct = e.get("cn_to","?")
            gf  = e.get("geom_from",""); gt = e.get("geom_to","")
            rxn = f"[{sl}]  ->  [{dl}] + H2O  (CN{cf}[{gf}]->CN{ct}[{gt}])"
        elif rtype == ReactionType.ASSOCIATION:
            nd = e.get("n_displaced",0)
            rxn = f"2x[{sl}]  ->  [{dl}]" + (f" + {nd}xH2O" if nd else "")
        elif rtype == ReactionType.DISSOCIATION:
            nd = e.get("n_displaced",0)
            rxn = f"[{sl}]  ->  2x[{dl}]" + (f" + {nd}xH2O" if nd else "")
        else:
            rxn = f"[{sl}]  ->  [{dl}]"

        e_s = f"  DeltaE={dE:+.3f}" if dE is not None else ""
        g_s = f"  DeltaG={dG:+.3f}" if dG is not None else ""
        return f"{rxn}{e_s}{g_s} eV"

    # -- visualisation ---------------------------------------------------------

    def plot(
        self,
        edge_label:   str        = "delta_e",
        max_label_eV: float      = 5.0,
        figsize:      Tuple      = (15, 9),
        title:        str        = "Reaction network (isodesmic)",
        show_broken:  bool       = True,
    ):
        """
        Draw the reaction network with matplotlib.

        Layout:  monomers (top row), dimers (middle), references (bottom).
        Node colour: blue=monomer, coral=dimer, grey=reference.
        Edge colour: green=substitution, brown=association/dissociation.
        Edge labels: DeltaE (or DeltaG) in eV where available and |val| < max_label_eV.

        Returns matplotlib.figure.Figure.
        """
        try:
            import matplotlib.pyplot as plt
            import matplotlib.patches as mpatches
        except ImportError:
            raise ImportError("pip install matplotlib")

        G = self.graph

        # -- node grouping -----------------------------------------------------
        monomers = [n for n,d in G.nodes(data=True) if d.get("structure")=="monomer"]
        dimers   = [n for n,d in G.nodes(data=True) if d.get("structure")=="dimer"]
        refs     = [n for n,d in G.nodes(data=True) if d.get("node_type")=="reference"]

        def _row_pos(nodes, y):
            n = len(nodes)
            return {node: (i * 2.4 - n * 1.2, y) for i, node in enumerate(nodes)}

        pos = {}
        pos.update(_row_pos(monomers, 2.5))
        pos.update(_row_pos(dimers,   0.0))
        pos.update(_row_pos(refs,    -2.5))

        # Nodes not placed yet (edge case): put at origin
        for n in G.nodes:
            if n not in pos:
                pos[n] = (0., 0.)

        # -- colours -----------------------------------------------------------
        NODE_COLOURS = {
            "monomer":   "#4A90D9",
            "dimer":     "#E07B54",
            "reference": "#B0BEC5",
        }
        node_colors = []
        for n, d in G.nodes(data=True):
            s = d.get("structure","")
            node_colors.append(NODE_COLOURS.get(s, "#9E9E9E"))

        EDGE_COLOURS = {
            ReactionType.SUBSTITUTION:    "#2E7D32",
            ReactionType.COORDINATION:    "#1565C0",   # blue -- CN increase
            ReactionType.DECOORDINATION:  "#1565C0",   # blue -- CN decrease
            ReactionType.ASSOCIATION:     "#6D4C41",
            ReactionType.DISSOCIATION:    "#6D4C41",
        }
        edge_colors = [EDGE_COLOURS.get(e.get("reaction_type",""), "#888")
                       for _,_,e in G.edges(data=True)]

        # -- draw --------------------------------------------------------------
        fig, ax = plt.subplots(figsize=figsize)
        ax.set_facecolor("#F5F7FA")
        ax.set_title(title, fontsize=13, fontweight="bold", pad=12)

        nx.draw_networkx_nodes(G, pos, ax=ax, node_size=650,
                               node_color=node_colors, alpha=0.93,
                               linewidths=0.8, edgecolors="#555")

        node_labels = {n: self.node_label(n).split("]")[-1].strip()[:16]
                       for n in G.nodes}
        nx.draw_networkx_labels(G, pos, labels=node_labels, ax=ax,
                                font_size=6.5, font_color="#111")

        # networkx >=3.2 requires connectionstyle as a plain string;
        # older builds (and some matplotlib versions) may receive a
        # ConnectionStyle object -- guard both cases.
        _cs = "arc3,rad=0.12"
        nx.draw_networkx_edges(G, pos, ax=ax, edge_color=edge_colors,
                               arrows=True, arrowsize=13, alpha=0.65,
                               connectionstyle=_cs, node_size=650)

        # Edge labels where DeltaE is available
        elabels = {}
        for s, d, e in G.edges(data=True):
            val = e.get(edge_label)
            if val is not None and abs(val) < max_label_eV:
                elabels[(s, d)] = f"{val:+.2f}"
        nx.draw_networkx_edge_labels(G, pos, edge_labels=elabels, ax=ax,
                                     font_size=5.5, label_pos=0.35,
                                     bbox=dict(fc="white", ec="none",
                                               boxstyle="round,pad=0.1", alpha=0.7))

        # Row annotations
        for y, lbl in [(2.5, "Monomers"), (0.0, "Dimers"), (-2.5, "References")]:
            ax.text(-max(len(monomers), len(dimers), len(refs)) * 1.2 - 0.5, y,
                    lbl, fontsize=8, color="#555", va="center", style="italic")

        # Legend
        legend = [
            mpatches.Patch(color=NODE_COLOURS["monomer"],   label="Monomer"),
            mpatches.Patch(color=NODE_COLOURS["dimer"],     label="Dimer"),
            mpatches.Patch(color=NODE_COLOURS["reference"], label="Reference (H2O, HCOOH, H2)"),
            mpatches.Patch(color="#2E7D32", label="Substitution (isodesmic)"),
            mpatches.Patch(color="#1565C0", label="Coordination / Decoordination (CN+/-1)"),
            mpatches.Patch(color="#6D4C41", label="Association / Dissociation"),
        ]
        if show_broken and self.broken_structures:
            n_br = len(self.broken_structures)
            fmls = ", ".join(m.formula for m, _ in self.broken_structures[:4])
            ax.text(0.01, 0.02,
                    f"! {n_br} BROKEN structure(s) excluded: {fmls}" +
                    ("..." if n_br > 4 else ""),
                    transform=ax.transAxes, fontsize=7, color="#C62828",
                    bbox=dict(fc="#FFEBEE", ec="#C62828", boxstyle="round,pad=0.3"))

        ax.legend(handles=legend, loc="upper right", fontsize=7,
                  framealpha=0.92, title="Legend", title_fontsize=7)
        ax.axis("off")
        plt.tight_layout()
        return fig

    # -- dataframe export ------------------------------------------------------

    def to_dataframe(self):
        """Return a pandas DataFrame with one row per directed edge."""
        try:
            import pandas as pd
        except ImportError:
            raise ImportError("pip install pandas")
        rows = []
        for src, dst, e in self.graph.edges(data=True):
            ns = self.graph.nodes[src]; nd = self.graph.nodes[dst]
            rows.append({
                "src_label":     self.node_label(src),
                "src_formula":   ns.get("formula",""),
                "src_geometry":  ns.get("geometry",""),
                "src_cn":        ns.get("cn",""),
                "src_ligands":   ns.get("ligands",""),
                "src_ox":        ns.get("ox_label",""),
                "dst_label":     self.node_label(dst),
                "dst_formula":   nd.get("formula",""),
                "dst_geometry":  nd.get("geometry",""),
                "dst_cn":        nd.get("cn",""),
                "dst_ligands":   nd.get("ligands",""),
                "reaction_type": e.get("reaction_type",""),
                "incoming":      e.get("incoming",""),
                "outgoing":      e.get("outgoing",""),
                "ref_in":        e.get("ref_in",""),
                "ref_out":       e.get("ref_out",""),
                "n_exchanged":   e.get("n_exchanged",""),
                "delta_e_eV":    e.get("delta_e"),
                "delta_g_eV":    e.get("delta_g"),
                "label":         e.get("label",""),
            })
        return pd.DataFrame(rows)

    def __repr__(self) -> str:
        return (f"ReactionNetwork("
                f"{self.graph.number_of_nodes()} nodes, "
                f"{self.graph.number_of_edges()} edges, "
                f"{len(self.broken_structures)} excluded)")


# -- Energy attachment helpers (used by generate_ni_complexes.py) -------------

def attach_energies_from_rows(net, rows: list,
                               backend: str, compute_thermo: bool,
                               T: float, P: float,
                               fmax: float, steps: int,
                               xtb_model=None, mace_model=None,
                               mace_device: str = "cpu") -> None:
    """
    Attach pre-computed energies from rows into reaction network graph nodes,
    then compute reference molecule energies (H2O, HCOOH, H2) at the same
    level and update all edge DeltaE / DeltaG values.
    """
    import warnings

    for node_id, node_data in net.graph.nodes(data=True):
        if node_data.get("node_type") != "complex":
            continue
        row  = node_data.get("row", {})
        e_ev = row.get("relax_energy_eV")
        g_ev = row.get("relax_gibbs_eV")
        if e_ev is not None:
            net.graph.nodes[node_id]["energy_eV"] = e_ev
        if g_ev is not None:
            net.graph.nodes[node_id]["gibbs_eV"]  = g_ev

    print("  Computing reference molecule energies (H2O, HCOOH, H2) ...")
    b = backend.lower()
    if compute_thermo:
        if b == "xtb+mace":
            from molbuilder.relaxation import xtb_relax_mace_singlepoint as _fn
            kwargs = dict(xtb_model=xtb_model, mace_model=mace_model,
                          mace_device=mace_device, compute_thermo=True,
                          T=T, P=P, fmax=fmax, steps=steps)
        else:
            from molbuilder.relaxation import thermochemistry as _fn
            kwargs = dict(backend=b, T=T, P=P, fmax=fmax, steps=steps)
    else:
        from molbuilder.relaxation import compute_energy as _fn
        kwargs = dict(backend=b.replace("+mace", ""))

    for node_id, node_data in net.graph.nodes(data=True):
        if node_data.get("node_type") != "reference":
            continue
        try:
            res = _fn(node_data["mol"], **kwargs)
            update = {"energy_eV": float(res.energy_eV)}
            if compute_thermo:
                update["gibbs_eV"] = float(res.gibbs_eV)
                update["_therm"]   = res
            net.graph.nodes[node_id].update(update)
            g_str = f"  G={res.gibbs_eV:.3f}" if compute_thermo else ""
            print(f"    {node_data['formula']:8s}  E={res.energy_eV:.3f}{g_str} eV")
        except Exception as exc:
            warnings.warn(f"Ref energy failed for {node_data.get('formula','?')}: {exc}")

    net._update_edge_energies()


def run_network_energies(net, backend: str, compute_thermo: bool,
                          T: float, P: float,
                          fmax: float, steps: int) -> None:
    """
    Compute energies for all network nodes via net.compute_energies().
    Falls back from xtb+mace to pure xTB (the hybrid requires Stage 1).
    """
    b = backend.lower()
    if b == "xtb+mace":
        b = "xtb"
        print("  Note: xtb+mace hybrid requires COMPUTE_ENERGY = True.")
        print("        Using pure xTB for reaction network energies.")
    net.compute_energies(
        backend=b, compute_thermo=compute_thermo,
        T=T, P=P, fmax=fmax, steps=steps, verbose=True,
    )
